document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
document.write( '    <script src=\"js/jquery-3.6.0.min.js\"></script>\n' );
document.write( '    <script src=\"js/all.js\"></script>\n' );
document.write( '    <link rel=\"stylesheet\" href=\"css/all.css\">\n' );
document.write( '    <link rel=\"Shortcut icon\" href=\"favicon.svg\">\n' );
document.write( '    <title>XXX | Li-Tang Chen</title>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '    <div class=\"botton-top\">\n' );
document.write( '        <a href=\"#\">top</a>\n' );
document.write( '    </div>\n' );
document.write( '    <div class=\"footer\">\n' );
document.write( '        <div class=\"name\">\n' );
document.write( '            <h2>LI-TANG CHEN</h2>\n' );
document.write( '            <p>來自台灣的\n' );
document.write( '                <br>\n' );
document.write( '                UI/UX Designer\n' );
document.write( '            </p>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"menu\">\n' );
document.write( '            <h3>更多作品</h3>\n' );
document.write( '            <ul>\n' );
document.write( '                <li><a href=\"uiux_cn.html\">UI/UX</a></li>\n' );
document.write( '                <li><a href=\"otherwork_cn.html\">影像作品</a></li>\n' );
document.write( '                <li><a href=\"aboutme_cn.html\">關於我</a></li>\n' );
document.write( '                <li><a target=\"_blank\" href=\"https://open.spotify.com/show/66hJQwL5yXUoQAaP17ePZq?si=E5F1xzBoRJa7DeLprDLEPw&dl_branch=1\">Podcast</a></li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"social\">\n' );
document.write( '            <h3>語言</h3>\n' );
document.write( '            <div class=\"icon\">\n' );
document.write( '                <ul>\n' );
document.write( '                    <li><a target=\"\" href=\"uiux.html\">English\n' );
document.write( '                    </a></li>\n' );
document.write( '                    <li><a target=\"\" href=\"uiux_cn.html\">\n' );
document.write( '                        中文\n' );
document.write( '                    </a></li>\n' );
document.write( '                </ul>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '</body>\n' );
document.write( '</html>' );
