document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
document.write( '    <script src=\"js/jquery-3.6.0.min.js\"></script>\n' );
document.write( '    <script src=\"js/all.js\"></script>\n' );
document.write( '    <link rel=\"stylesheet\" href=\"css/all.css\">\n' );
document.write( '    <link rel=\"Shortcut icon\" href=\"favicon.svg\">\n' );
document.write( '    <title>XXX | Li-Tang Chen</title>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '    <div class=\"header\">\n' );
document.write( '        <div class=\"logo\">\n' );
document.write( '            <h1><a href=\"uiux.html\">Tang\'s Portfolio</a></h1>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"menu\">\n' );
document.write( '            <ul>\n' );
document.write( '                <li><a href=\"uiux.html\">UI/UX</a></li>\n' );
document.write( '                <li><a href=\"otherwork.html\">Motion</a></li>\n' );
document.write( '                <li><a href=\"aboutme.html\">About me</a></li>\n' );
document.write( '                <li><a href=\"#\" class=\"contact-buttom\">Contact</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '    <div class=\"shade\"></div>\n' );
document.write( '    <div class=\"contact\">\n' );
document.write( '        <h2>Contact me</h2>\n' );
document.write( '        <div class=\"box\">\n' );
document.write( '            <h3>Email</h3>\n' );
document.write( '            <p>mz036434@gmail.com</p>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"box\">\n' );
document.write( '            <h3>Phone</h3>\n' );
document.write( '            <p>+886 972-699-690</p>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"box\">\n' );
document.write( '            <h3>Social Media</h3>\n' );
document.write( '            <div class=\"image\">\n' );
document.write( '                <a target=\"_blank\" href=\"https://www.facebook.com/profile.php?id=1378490222\">\n' );
document.write( '                    <img src=\"image/contact/fb_icon.svg\" alt=\"\"></a>\n' );
document.write( '                    <a target=\"_blank\" href=\"https://www.instagram.com/tang_breaks_silence/\">\n' );
document.write( '                    <img src=\"image/contact/instagram_icon.svg\" alt=\"\"></a>\n' );
document.write( '                    <a target=\"_blank\" href=\"https://www.linkedin.com/in/litang-chen-0712a3198/\">\n' );
document.write( '                    <img class=\"linedin-icon\" src=\"image/contact/Linkedin_icon.svg\" alt=\"\"></a>\n' );
document.write( '            </div>\n' );
document.write( '            \n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"cancel\">\n' );
document.write( '            <a class=\"cancel_buttom\" href=\"#\">Back</a>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '</body>\n' );
document.write( '</html>' );
